ENV["VAGRANT_DEFAULT_PROVIDER"] = "vmware_desktop"

Vagrant.require_version ">= 2.3.0"

BOX_IMAGE = "generic/ubuntu2204"

Vagrant.configure("2") do |config|
  config.vm.box = BOX_IMAGE

  config.vm.define "standalone" do |standalone|
    standalone.vm.hostname = "splunk"

    standalone.vm.synced_folder ".", "/vagrant", disabled: true

    standalone.vm.provider "vmware_desktop" do |v|
      v.cpus = 1
      v.memory = 1024
    end

    standalone.vm.provision "shell",
      path: "../scripts/splunk_install.sh",
      env: {
        "ADMIN_PWD" => "adminuser123!"
      }
  end
end

Vagrant.configure("2") do |config|
  config.vm.box = BOX_IMAGE

  config.vm.define "uf" do |uf|
    uf.vm.hostname = "splunk-uf"

    uf.vm.synced_folder ".", "/vagrant", disabled: true

    uf.vm.provider "vmware_desktop" do |v|
      v.cpus = 1
      v.memory = 1024
    end
  end
end